# Generated by Django 5.1.2 on 2024-10-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=7)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('transportation', 'Transportation'), ('clothes', 'Clothes'), ('education', 'Education'), ('fitness', 'Fitness'), ('gifts', 'Gifts'), ('food', 'Food'), ('health', 'Health'), ('furniture', 'Furniture'), ('pet', 'Pet'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('others', 'Others'), ('allowance', 'Allowance'), ('awards', 'Awards'), ('bonus', 'Bonus'), ('investment', 'Investment'), ('lottery', 'Lottery'), ('salary', 'Salary'), ('tips', 'Tips'), ('others', 'Others')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
