# Generated by Django 5.1.2 on 2024-10-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('bills', 'Bills'), ('transportation', 'Transportation'), ('clothes', 'Clothes'), ('education', 'Education'), ('fitness', 'Fitness'), ('gifts', 'Gifts'), ('food', 'Food'), ('health', 'Health'), ('furniture', 'Furniture'), ('pet', 'Pet'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('others', 'Others'), ('allowance', 'Allowance'), ('awards', 'Awards'), ('bonus', 'Bonus'), ('investment', 'Investment'), ('lottery', 'Lottery'), ('salary', 'Salary'), ('tips', 'Tips'), ('others', 'Others')], max_length=20),
        ),
    ]
